[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
authors = ["Jeff Weber <jweber@cofront.net>"]
publish = false

[dependencies]
atoi = "0.4"
#reqwest = { version = "0.11", features = ["blocking"]}
